#%RAML 1.0 DataType
type: object
displayName: "User table"
properties:
  USER_ID:
    type: string
    required: true
    displayName: "USER_ID"
    example: "00u3t6kba9dUpqi3f5d7"
  EMAIL_ID:
    type: string
    required: true
    displayName: "EMAIL_ID"
    example: "mimo@gmail.com"
  STATUS_TYPE_ID:
    type: number
    required: true
    displayName: "STATUS_TYPE_ID"
    example: 2
  FIRST_NAME:
    type: string
    required: true
    displayName: "FIRST_NAME"
    example: "Anitha"
  LAST_NAME:
    type: string
    required: true
    displayName: "LAST_NAME"
    example: "David"
  PHONE_NUMBER:
    type: number
    required: true
    displayName: "PHONE_NUMBER"
    example: 987654321
  